version: '3'

services:
  backend:
    image: ghcr.io/korjavin/miniwebpocbot-backend:latest
    container_name: prediction-game-backend
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PUBLIC_WEBAPP_URL=${PUBLIC_WEBAPP_URL}
    networks:
      - prediction-game-network

  frontend:
    image: ghcr.io/korjavin/miniwebpocbot-frontend:latest
    container_name: prediction-game-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_PB_URL=${NEXT_PUBLIC_PB_URL}
      - PUBLIC_WEBAPP_URL=${PUBLIC_WEBAPP_URL}
    depends_on:
      - backend
    networks:
      - prediction-game-network

networks:
  prediction-game-network:
    driver: bridge

volumes:
  pb_data:
    driver: local
